"""initial schema

Revision ID: 4a8572467c0e
Revises: 
Create Date: 2026-09-03 16:46:21.711280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a8572467c0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('event_seq', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_created_at'), 'workspaces', ['created_at'], unique=False)
    op.create_index(op.f('ix_workspaces_token_hash'), 'workspaces', ['token_hash'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('source_format', sa.Enum('pdf', 'image', 'docx', 'xlsx', 'csv', 'text', name='source_format', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'parsed', 'extracting', 'awaiting_schema', 'done', 'failed', name='document_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('stage_detail', sa.String(length=256), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index('ix_documents_workspace_created', 'documents', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_documents_workspace_status', 'documents', ['workspace_id', 'status'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('presentation', sa.String(length=32), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_created_at'), 'queries', ['created_at'], unique=False)
    op.create_index('ix_queries_workspace_created', 'queries', ['workspace_id', 'created_at'], unique=False)
    op.create_table('schema_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=16), server_default='model', nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['schema_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'version', name='uq_schema_versions_ws_version')
    )
    op.create_index(op.f('ix_schema_versions_created_at'), 'schema_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_schema_versions_workspace_id'), 'schema_versions', ['workspace_id'], unique=False)
    op.create_table('workspace_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'seq', name='uq_workspace_events_ws_seq')
    )
    op.create_index(op.f('ix_workspace_events_created_at'), 'workspace_events', ['created_at'], unique=False)
    op.create_index('ix_workspace_events_ws_seq', 'workspace_events', ['workspace_id', 'seq'], unique=False)
    op.create_table('document_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('open', 'guided', 'backfill')", name='ck_extraction_kind'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_extractions_created_at'), 'document_extractions', ['created_at'], unique=False)
    op.create_index('ix_extractions_document_kind', 'document_extractions', ['document_id', 'kind'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('width_pt', sa.Float(), nullable=False),
    sa.Column('height_pt', sa.Float(), nullable=False),
    sa.Column('image_key', sa.String(length=512), nullable=True),
    sa.Column('ocr_applied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('locator', sa.String(length=128), nullable=True),
    sa.Column('text_layer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'index', name='uq_pages_document_index')
    )
    op.create_index(op.f('ix_pages_document_id'), 'pages', ['document_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('initial_schema', 'drift')", name='ck_proposal_kind'),
    sa.CheckConstraint("status IN ('pending', 'applied', 'dismissed')", name='ck_proposal_status'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_created_at'), 'proposals', ['created_at'], unique=False)
    op.create_index('ix_proposals_workspace_status', 'proposals', ['workspace_id', 'status'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('schema_version_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_records_document')
    )
    op.create_index(op.f('ix_records_created_at'), 'records', ['created_at'], unique=False)
    op.create_index('ix_records_workspace_created', 'records', ['workspace_id', 'created_at'], unique=False)
    op.create_table('field_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_type', sa.Enum('string', 'number', 'currency', 'date', 'boolean', 'enum', 'string_list', name='field_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tier', sa.Enum('high', 'medium', 'low', 'conflict', 'verified', name='value_tier', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('model', 'human_verified', 'not_present', name='value_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_value_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_run_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'field_key', name='uq_field_values_record_field')
    )
    op.create_index('ix_field_values_human_owned', 'field_values', ['record_id'], unique=False, postgresql_where="status IN ('human_verified', 'not_present')")
    op.create_index('ix_field_values_tier', 'field_values', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_field_values_tier', table_name='field_values')
    op.drop_index('ix_field_values_human_owned', table_name='field_values', postgresql_where="status IN ('human_verified', 'not_present')")
    op.drop_table('field_values')
    op.drop_index('ix_records_workspace_created', table_name='records')
    op.drop_index(op.f('ix_records_created_at'), table_name='records')
    op.drop_table('records')
    op.drop_index('ix_proposals_workspace_status', table_name='proposals')
    op.drop_index(op.f('ix_proposals_created_at'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_pages_document_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index('ix_extractions_document_kind', table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_created_at'), table_name='document_extractions')
    op.drop_table('document_extractions')
    op.drop_index('ix_workspace_events_ws_seq', table_name='workspace_events')
    op.drop_index(op.f('ix_workspace_events_created_at'), table_name='workspace_events')
    op.drop_table('workspace_events')
    op.drop_index(op.f('ix_schema_versions_workspace_id'), table_name='schema_versions')
    op.drop_index(op.f('ix_schema_versions_created_at'), table_name='schema_versions')
    op.drop_table('schema_versions')
    op.drop_index('ix_queries_workspace_created', table_name='queries')
    op.drop_index(op.f('ix_queries_created_at'), table_name='queries')
    op.drop_table('queries')
    op.drop_index('ix_documents_workspace_status', table_name='documents')
    op.drop_index('ix_documents_workspace_created', table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_workspaces_token_hash'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_created_at'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
