"""v2 pivot: chunks, chat messages, dashboards; drop proposals and queries

Adds the three tables the v2 product needs (decision D34):

* ``chunks``        retrievable passages with word spans and vectors (D35, D36, D45)
* ``chat_messages`` the persisted conversation (D44)
* ``dashboards``    the agent-generated panels (D40)

Drops the two that went with the features they served: ``proposals`` (the schema review
loop, D38) and ``queries`` (the natural-language-to-SQL log, D35).

Also widens the ``document_status`` CHECK, because the pipeline gained a ``parsing`` and an
``indexing`` stage and lost ``parsed``. Existing rows are migrated before the constraint is
swapped, since adding it first would fail against them.

HAND-EDITED, AND DO NOT REGENERATE
-----------------------------------
``alembic revision --autogenerate`` additionally proposed dropping five UNRELATED check
constraints: ``source_format`` on ``documents``, ``field_type``, ``value_status`` and
``value_tier`` on ``field_values``, and ``schema_change_author`` on ``schema_versions``.

That is the same false positive the previous migration documented: autogenerate cannot
round-trip the constraint text ``Enum(native_enum=False)`` renders, so it reads every one of
them as removed. Applying the suggestion would have silently deleted validation on the most
safety-critical columns in the schema, ``value_status`` among them, which is the column the
never-lose-a-human-correction guarantee is enforced through. Those five drops are removed
here deliberately.

Revision ID: 549ff277681a
Revises: 6c1b65b8e15d
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '549ff277681a'
down_revision: Union[str, Sequence[str], None] = '6c1b65b8e15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chat_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('streaming', 'done', 'stopped', 'failed', name='chat_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visual', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('surface', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_run_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index('ix_chat_messages_workspace_created', 'chat_messages', ['workspace_id', 'created_at'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'failed', name='dashboard_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('stale', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('panels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_run_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', name='uq_dashboards_workspace')
    )
    op.create_index(op.f('ix_dashboards_created_at'), 'dashboards', ['created_at'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=True),
    sa.Column('word_start', sa.Integer(), nullable=True),
    sa.Column('word_end', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_digest', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_chunks_document_ordinal')
    )
    op.create_index(op.f('ix_chunks_created_at'), 'chunks', ['created_at'], unique=False)
    op.create_index('ix_chunks_document', 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_workspace', 'chunks', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_queries_created_at'), table_name='queries')
    op.drop_index(op.f('ix_queries_workspace_created'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_proposals_created_at'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_workspace_status'), table_name='proposals')
    op.drop_table('proposals')
    # This one constraint genuinely has to be swapped: `parsing` and `indexing` are new
    # statuses and `parsed` is gone. Rows migrate FIRST, because adding the new constraint
    # while a row still reads 'parsed' would fail the whole migration.
    op.execute("UPDATE documents SET status = 'parsing' WHERE status = 'parsed'")
    op.drop_constraint("document_status", "documents", type_="check")
    op.create_check_constraint(
        "document_status",
        "documents",
        "status IN ('uploaded', 'parsing', 'extracting', 'awaiting_schema', "
        "'indexing', 'done', 'failed')",
    )
    # The five other CHECK constraints autogenerate wanted dropped here are left ALONE on
    # purpose. See the module docstring.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE documents SET status = 'parsed' WHERE status IN ('parsing', 'indexing')"
    )
    op.drop_constraint("document_status", "documents", type_="check")
    op.create_check_constraint(
        "document_status",
        "documents",
        "status IN ('uploaded', 'parsed', 'extracting', 'awaiting_schema', 'done', 'failed')",
    )
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('kind', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("kind::text = ANY (ARRAY['initial_schema'::character varying, 'drift'::character varying]::text[])", name=op.f('ck_proposal_kind')),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'applied'::character varying, 'dismissed'::character varying]::text[])", name=op.f('ck_proposal_status')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('proposals_document_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('proposals_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('proposals_pkey'))
    )
    op.create_index(op.f('ix_proposals_workspace_status'), 'proposals', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_proposals_created_at'), 'proposals', ['created_at'], unique=False)
    op.create_table('queries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sql', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('presentation', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('row_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('queries_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('queries_pkey'))
    )
    op.create_index(op.f('ix_queries_workspace_created'), 'queries', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_queries_created_at'), 'queries', ['created_at'], unique=False)
    op.drop_index('ix_chunks_workspace', table_name='chunks')
    op.drop_index('ix_chunks_document', table_name='chunks')
    op.drop_index(op.f('ix_chunks_created_at'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_dashboards_created_at'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index('ix_chat_messages_workspace_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
