"""constrain schema_versions.created_by

Gives ``schema_versions.created_by`` the same treatment every other enumerated column in the
model already had: a VARCHAR with a CHECK constraint listing the permitted values. Decisions
D23 and D25 turned this column into the thing that distinguishes "the system changed your
schema without asking" from "you changed it", which the history view renders and the whole
confidence-gated auto-apply design rests on. An unconstrained VARCHAR there meant a typo
could produce a silently mislabelled audit entry.

The old vocabulary was a single default value, ``'model'``. It becomes ``'model_auto'``, and
existing rows are migrated before the constraint is added, since adding it first would fail
against them.

WRITTEN BY HAND, NOT LEFT AS AUTOGENERATED
------------------------------------------
``alembic revision --autogenerate`` additionally proposed dropping five unrelated CHECK
constraints: ``document_status`` and ``source_format`` on ``documents``, and ``field_type``,
``value_status`` and ``value_tier`` on ``field_values``. That is a known false positive with
``Enum(native_enum=False)`` — autogenerate cannot round-trip the rendered constraint text, so
it reads every one of them as removed. Applying that suggestion would have quietly deleted
the validation on the most safety-critical columns in the schema, including the ``status``
column the never-lose-a-correction guarantee is enforced through. Those drops are removed
here deliberately; do not regenerate this file.

Revision ID: 6c1b65b8e15d
Revises: 4a8572467c0e
Create Date: 2026-09-04 01:49:32.997309
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6c1b65b8e15d"
down_revision: str | Sequence[str] | None = "4a8572467c0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CONSTRAINT_NAME = "schema_change_author"
PERMITTED = ("model_auto", "user")


def upgrade() -> None:
    # Widen and re-default first. The column has to be able to hold 'model_auto' before any
    # row is set to it, and the old default has to stop applying to new inserts.
    op.alter_column(
        "schema_versions",
        "created_by",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
        server_default="model_auto",
    )

    # Then migrate existing rows. Any value outside the new vocabulary is left alone on
    # purpose: the constraint below will refuse it loudly rather than this migration guessing
    # what it was supposed to mean.
    op.execute("UPDATE schema_versions SET created_by = 'model_auto' WHERE created_by = 'model'")

    op.create_check_constraint(
        CONSTRAINT_NAME,
        "schema_versions",
        sa.column("created_by").in_(PERMITTED),
    )


def downgrade() -> None:
    op.drop_constraint(CONSTRAINT_NAME, "schema_versions", type_="check")
    op.execute("UPDATE schema_versions SET created_by = 'model' WHERE created_by = 'model_auto'")
    op.alter_column(
        "schema_versions",
        "created_by",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
        server_default="model",
    )
