"""blobs: object storage in the database

Adds the one table ``app.storage.postgres`` uses. Decision D86.

Written by hand rather than autogenerated, for the same reason the two migrations before it
say so: ``--autogenerate`` on this schema proposes dropping unrelated CHECK constraints it
did not create, and a migration that quietly removes validation is worse than one typed out.

Revision ID: b1c0d2e3f4a5
Revises: 549ff277681a
Create Date: 2026-09-06

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b1c0d2e3f4a5"
down_revision: str | Sequence[str] | None = "549ff277681a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "blobs",
        sa.Column("key", sa.String(length=1024), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )


def downgrade() -> None:
    op.drop_table("blobs")
