/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and readiness */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an anonymous workspace */
        post: operations["create_workspace_api_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema, documents, and counts for a cold start */
        get: operations["get_workspace_api_v1_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload one or more documents */
        post: operations["upload_api_v1_workspaces__workspace_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load the sample documents
         * @description Load the curated sample set. Requirement FR-05, decision D15.
         *
         *     Reads ``samples/manifest.json`` rather than hard-coding filenames, so dropping files
         *     into ``samples/`` is the only step needed to change the demo corpus.
         */
        post: operations["seed_api_v1_workspaces__workspace_id__documents_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One document */
        get: operations["get_document_api_v1_workspaces__workspace_id__documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete a document */
        delete: operations["delete_document_api_v1_workspaces__workspace_id__documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The original file, with byte-range support
         * @description Stream the original. Range requests are supported because pdf.js relies on them.
         *
         *     Without ranges, opening page one of a fifty megabyte scan downloads all fifty
         *     megabytes first, which is the difference between a viewer that feels instant and one
         *     that does not.
         */
        get: operations["original_file_api_v1_workspaces__workspace_id__documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents/{document_id}/pages/{page_index}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A rendered page image */
        get: operations["page_image_api_v1_workspaces__workspace_id__documents__document_id__pages__page_index__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents/{document_id}/reextract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-run extraction, preserving human corrections
         * @description Re-run the pipeline for one document. Requirement FR-34.
         *
         *     Human-verified values survive by construction: the write path filters them out and a
         *     disagreeing model answer is recorded beside the human's rather than over it. See
         *     ``app.pipeline.persist`` and decision D16.
         */
        post: operations["reextract_api_v1_workspaces__workspace_id__documents__document_id__reextract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Records, cursor paged */
        get: operations["list_records_api_v1_workspaces__workspace_id__records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/records/{record_id}/fields/{field_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Correct one value
         * @description Record a human decision about one value. Requirements FR-23 and FR-34.
         *
         *     From this point the value is immune to re-extraction: the write path filters
         *     human-owned rows, and a later model answer that disagrees is stored beside it rather
         *     than over it (decision D16).
         */
        patch: operations["correct_field_api_v1_workspaces__workspace_id__records__record_id__fields__field_key__patch"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The review queue
         * @description Cells needing attention, highest impact first. Requirement FR-32.
         *
         *     Ordered by impact rather than by tier alone, because "which of these low-confidence
         *     cells matters" is the question a user actually has: a shaky total on an invoice is worth
         *     more attention than a shaky note.
         */
        get: operations["review_queue_api_v1_workspaces__workspace_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current schema */
        get: operations["get_schema_api_v1_workspaces__workspace_id__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit the schema */
        patch: operations["update_schema_api_v1_workspaces__workspace_id__schema_patch"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/schema/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Schema history
         * @description Requirement FR-15. Marks which entries the system applied without asking.
         */
        get: operations["schema_history_api_v1_workspaces__workspace_id__schema_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/schema/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revert the schema
         * @description Requirement FR-15's one-click revert.
         *
         *     Applies the old fields as a NEW version rather than deleting rows, so the history keeps
         *     both the mistake and the correction.
         */
        post: operations["revert_schema_api_v1_workspaces__workspace_id__schema_revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Outstanding schema questions
         * @description Only questions that needed a human live here. Decision D23.
         *
         *     An automatically applied change writes a ``schema_versions`` row and no proposal, so
         *     "how many decisions are outstanding" is a row count rather than a filtered one.
         */
        get: operations["list_proposals_api_v1_workspaces__workspace_id__proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/proposals/{proposal_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide a schema question */
        post: operations["resolve_proposal_api_v1_workspaces__workspace_id__proposals__proposal_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live workspace events (Server-Sent Events) */
        get: operations["events_api_v1_workspaces__workspace_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BBox
         * @description An axis-aligned box in top-left-origin page points. See the module docstring.
         */
        BBox: {
            /**
             * X0
             * @description Left edge, points from the left of the page.
             */
            x0: number;
            /**
             * Top
             * @description Top edge, points from the TOP of the page.
             */
            top: number;
            /**
             * X1
             * @description Right edge, points from the left of the page.
             */
            x1: number;
            /**
             * Bottom
             * @description Bottom edge, points from the TOP of the page.
             */
            bottom: number;
        };
        /** Body_upload_api_v1_workspaces__workspace_id__documents_post */
        Body_upload_api_v1_workspaces__workspace_id__documents_post: {
            /**
             * Files
             * @description One or more documents.
             */
            files: string[];
        };
        /** CheckResult */
        CheckResult: {
            /** Ok */
            ok: boolean;
            /** Detail */
            detail?: string | null;
        };
        /**
         * CorrectionRequest
         * @description Either a value, or an assertion that the field is absent from this document.
         */
        CorrectionRequest: {
            /** Value */
            value?: unknown | null;
            /**
             * Not Present
             * @description The user asserts this document does not contain this field. A correction in its own right, and protected from re-extraction the same way an edited value is.
             * @default false
             */
            not_present: boolean;
        };
        /** CreateWorkspaceRequest */
        CreateWorkspaceRequest: {
            /** Label */
            label?: string | null;
        };
        /** CreateWorkspaceResponse */
        CreateWorkspaceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Token
             * @description Bearer token for every subsequent request. Returned ONCE and never recoverable: only its hash is stored. Anyone holding it has full access to this workspace, which is the accepted tradeoff of having no accounts (decision D8).
             */
            token: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Mime */
            mime: string;
            source_format: components["schemas"]["SourceFormat"];
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["DocumentStatus"];
            /** Stage Detail */
            stage_detail: string | null;
            /** Failure Reason */
            failure_reason: string | null;
            /** Page Count */
            page_count: number | null;
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Pages
             * @description Per-page dimensions IN POINTS plus the image path. The viewer divides the width it actually rendered by `width_pt` to get its overlay scale, so it never needs to know about dots per inch.
             */
            pages?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DocumentStatus
         * @description Where a document is in the pipeline. Rendered directly as the progress list.
         *
         *     The observability requirement and the user experience are the same feature here: the
         *     progress list in the interface IS this state machine, so every state has to be a state
         *     a person would want to see, and every transition publishes an event.
         *
         *     Transitions::
         *
         *         uploaded -> parsed -> extracting -> awaiting_schema -> done
         *              |         |          |               |
         *              +---------+----------+---------------+--> failed
         *
         *     ``awaiting_schema`` is the state review finding 8.5 introduced. A document in the very
         *     first batch finishes open extraction before the workspace has a schema, so it cannot
         *     produce records yet. Without this state the interface would have to show it as either
         *     still working (a lie) or done (also a lie, since no row appeared).
         * @enum {string}
         */
        DocumentStatus: "uploaded" | "parsed" | "extracting" | "awaiting_schema" | "done" | "failed";
        /** DocumentSummary */
        DocumentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            status: components["schemas"]["DocumentStatus"];
            /** Stage Detail */
            stage_detail?: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Page Count */
            page_count?: number | null;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FieldSpec
         * @description One field in a workspace's schema, as the user has agreed to it.
         */
        FieldSpec: {
            /**
             * Key
             * @description Column name in the generated view. Machine identifier.
             */
            key: string;
            /**
             * Label
             * @description What the interface shows a person.
             */
            label: string;
            type: components["schemas"]["FieldType"];
            /**
             * Description
             * @description What this field means. Sent to the model during schema-guided extraction, and used for similarity matching during drift detection.
             * @default
             */
            description: string;
            /**
             * Enum Values
             * @description Permitted values, for FieldType.ENUM only.
             */
            enum_values?: string[] | null;
            /**
             * Currency Default
             * @description ISO 4217 code assumed when a document states an amount with no currency marker, for FieldType.CURRENCY only.
             */
            currency_default?: string | null;
            /**
             * Source Keys
             * @description The raw keys from open extraction that were unified into this field. Kept so the user can see WHY a field exists, and so drift detection knows which aliases have already been resolved.
             */
            source_keys?: string[];
            /**
             * Weight
             * @description Review priority multiplier. The review queue orders by weight * (1 - confidence), so a wrong total matters more than a wrong note. Currency and date fields default higher, set in app.schema.propose.
             * @default 1
             */
            weight: number;
        };
        /**
         * FieldType
         * @description The supported field types. Requirement FR-12.
         *
         *     The stored representation of each is documented in ``app.domain.values``, which is the
         *     only module that converts between a raw model output and one of these.
         * @enum {string}
         */
        FieldType: "string" | "number" | "currency" | "date" | "boolean" | "enum" | "string_list";
        /**
         * FieldValue
         * @description One extracted or corrected value, with everything needed to trust it.
         */
        FieldValue: {
            /** Field Key */
            field_key: string;
            /**
             * Value
             * @description The value, in the stored representation for its type. Null means the field is genuinely absent from this document, not that extraction failed.
             */
            value?: unknown | null;
            value_type: components["schemas"]["FieldType"];
            /**
             * Confidence
             * @description The model's self-report. Never the tier.
             */
            confidence?: number | null;
            tier: components["schemas"]["Tier"];
            /** @default model */
            status: components["schemas"]["ValueStatus"];
            provenance?: components["schemas"]["Provenance"] | null;
            /** Model Value */
            model_value?: unknown | null;
            /** Model Value At */
            model_value_at?: string | null;
        };
        /**
         * GroundingFailure
         * @description Why a value could not be located in its document.
         *
         *     Recorded rather than swallowed. A value that cannot be grounded has its tier capped at
         *     low (see ``app.pipeline.score``), and this is the reason the interface shows the user.
         *     An ungroundable value is the strongest hallucination signal we have: a value the model
         *     invented has no quote to find. See decision D5.
         * @enum {string}
         */
        GroundingFailure: "no_quote" | "quote_not_found" | "page_out_of_range" | "no_text_layer";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Environment */
            environment: string;
            /**
             * Process Id
             * @description Operating system process identifier. The in-process worker queue and event bus require exactly one API process, so seeing this value change between requests means the deployment is misconfigured. See decision D9.
             */
            process_id: number;
            database: components["schemas"]["CheckResult"];
            storage: components["schemas"]["CheckResult"];
            llm: components["schemas"]["CheckResult"];
        };
        /** ProposalList */
        ProposalList: {
            /** Proposals */
            proposals: components["schemas"]["ProposalSummary"][];
        };
        /** ProposalSummary */
        ProposalSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Document Id */
            document_id: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Provenance
         * @description The trail from a value back to the pixels it came from.
         *
         *     An empty ``boxes`` list with a populated ``failure`` is a legitimate, fully described
         *     state: we have a value, we know the model's justification for it, and we are telling the
         *     user honestly that we could not find that justification in the document.
         */
        Provenance: {
            /**
             * Page Index
             * @description Zero-based page the value was found on, if known.
             */
            page_index?: number | null;
            /**
             * Boxes
             * @description One box per visual line of the matched quote. Empty means grounding failed, in which case `failure` says why. Multiple boxes rather than one union box, because a quote that wraps must not highlight the content between its fragments (requirement FR-30).
             */
            boxes?: components["schemas"]["BBox"][];
            /**
             * Quote
             * @description The verbatim span the model cited as evidence. Shown to the user in the viewer side card (requirement FR-31).
             */
            quote?: string | null;
            /**
             * Reasoning
             * @description The model's short justification for this value. FR-31.
             */
            reasoning?: string | null;
            /**
             * Match Score
             * @description Fuzzy match score of the quote against the page text, 0 to 100. Feeds tier derivation.
             */
            match_score?: number | null;
            /**
             * Locator
             * @description Human-readable address within the source, for formats where one is meaningful: 'Sheet1!B7', 'paragraph 12', 'line 48'. Display only, never parsed.
             */
            locator?: string | null;
            /** @description Set if and only if `boxes` is empty. */
            failure?: components["schemas"]["GroundingFailure"] | null;
        };
        /**
         * Record
         * @description One row of the unified table.
         */
        Record: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Document Name
             * @description Original filename. Shown as the row's identity.
             */
            document_name: string;
            /** Schema Version */
            schema_version: number;
            /**
             * Values
             * @description Keyed by field key. A field absent from this mapping was never extracted for this document, which is different from a field present with a null value, which means the document genuinely does not contain it.
             */
            values?: {
                [key: string]: components["schemas"]["FieldValue"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RecordPage
         * @description A cursor-paged slice of records.
         */
        RecordPage: {
            /** Records */
            records: components["schemas"]["Record"][];
            /**
             * Next Cursor
             * @description Opaque. Pass back as `cursor` for the next page.
             */
            next_cursor?: string | null;
            /**
             * Total
             * @description Total records in the workspace, for the row count.
             */
            total: number;
        };
        /** ReextractResponse */
        ReextractResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Message */
            message: string;
        };
        /** RejectedUpload */
        RejectedUpload: {
            /** Filename */
            filename: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * ResolveProposalRequest
         * @description The user's decision on a proposal card. Requirement FR-13's three actions.
         */
        ResolveProposalRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "map" | "add" | "ignore" | "merge";
            /**
             * Target Key
             * @description For 'map', the existing field to map onto. For 'merge', the field to merge into.
             */
            target_key?: string | null;
            /** @description For 'add', the field to create, so the user can rename or retype it before it lands. */
            field?: components["schemas"]["FieldSpec"] | null;
        };
        /** RevertRequest */
        RevertRequest: {
            /** Version */
            version: number;
        };
        /**
         * ReviewItem
         * @description One cell that wants a human's attention.
         */
        ReviewItem: {
            /**
             * Record Id
             * Format: uuid
             */
            record_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Field Key */
            field_key: string;
            /** Field Label */
            field_label: string;
            value: components["schemas"]["FieldValue"];
            /**
             * Impact
             * @description Ordering score: field weight times uncertainty, with a conflict outranking a suspicion at the same weight. See app.pipeline.score.impact.
             */
            impact: number;
        };
        /** ReviewQueue */
        ReviewQueue: {
            /** Items */
            items: components["schemas"]["ReviewItem"][];
            /** Total */
            total: number;
        };
        /**
         * SchemaChangeAuthor
         * @description Who applied a schema version. Decisions D23 and D24.
         *
         *     Load-bearing rather than decorative: this is what the history view reads to mark an
         *     entry "applied automatically", and it is the audit trail that makes confidence-gated
         *     auto-apply defensible. A change the system made without asking has to be as visible
         *     afterwards as one the user made deliberately, so both are the same kind of row and this
         *     column is the only thing distinguishing them.
         *
         *     Never the workspace token itself. Only its hash is ever stored (decision D8).
         * @enum {string}
         */
        SchemaChangeAuthor: "model_auto" | "user";
        /** SchemaHistory */
        SchemaHistory: {
            /** Versions */
            versions: components["schemas"]["SchemaVersionSummary"][];
        };
        /** SchemaResponse */
        SchemaResponse: {
            /** Version */
            version: number | null;
            /** Fields */
            fields?: components["schemas"]["FieldSpec"][];
        };
        /** SchemaVersionSummary */
        SchemaVersionSummary: {
            /** Version */
            version: number;
            created_by: components["schemas"]["SchemaChangeAuthor"];
            /** Change Summary */
            change_summary: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Field Count */
            field_count: number;
            /** Is Current */
            is_current: boolean;
        };
        /** SeedResponse */
        SeedResponse: {
            /** Loaded */
            loaded?: components["schemas"]["UploadedDocument"][];
            /** Missing */
            missing?: string[];
            /** Message */
            message: string;
        };
        /**
         * SourceFormat
         * @description Formats Distill can parse. Requirement FR-02.
         * @enum {string}
         */
        SourceFormat: "pdf" | "image" | "docx" | "xlsx" | "csv" | "text";
        /**
         * Tier
         * @description How much a value should be trusted. Always DERIVED, never asked of the model.
         *
         *     See decision D5 and the table in implementation.md section 6.4. The derivation lives in
         *     ``app.pipeline.score`` and nowhere else.
         * @enum {string}
         */
        Tier: "high" | "medium" | "low" | "conflict" | "verified";
        /**
         * UpdateSchemaRequest
         * @description The complete new field list. Requirement FR-11.
         *
         *     A whole list rather than a patch, deliberately: renames, retypes, removals, and
         *     reorderings all become one shape, and the server never has to infer intent from a
         *     sequence of operations.
         */
        UpdateSchemaRequest: {
            /** Fields */
            fields: components["schemas"]["FieldSpec"][];
            /**
             * Summary
             * @description What you changed, for the history view.
             */
            summary?: string | null;
        };
        /**
         * UploadResponse
         * @description Partial success is the normal case, so accepted and rejected come back together.
         *
         *     One unreadable file in a drop of twelve must not fail the other eleven, which is
         *     guarantee 3 in the backend plan and requirement 3.6.
         */
        UploadResponse: {
            /** Accepted */
            accepted?: components["schemas"]["UploadedDocument"][];
            /** Rejected */
            rejected?: components["schemas"]["RejectedUpload"][];
        };
        /** UploadedDocument */
        UploadedDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            status: components["schemas"]["DocumentStatus"];
            /** Size Bytes */
            size_bytes: number;
            source_format: components["schemas"]["SourceFormat"];
            /** Detected Mime */
            detected_mime: string;
            /**
             * Note
             * @description Set when the file's contents disagree with its extension. The content decides which parser runs; this explains what we concluded.
             */
            note?: string | null;
            /**
             * Duplicate Of
             * @description Set when this exact file is already in the workspace. The upload is accepted and points at the existing document rather than processing it twice.
             */
            duplicate_of?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValueStatus
         * @description Where a value came from. Drives the never-lose-a-correction guarantee.
         *
         *     Every write path a model can reach filters on ``status <> 'human_verified'``. This is
         *     enforced in SQL rather than by convention, which is what makes principle 4 of
         *     requirements.md a guarantee instead of an intention.
         * @enum {string}
         */
        ValueStatus: "model" | "human_verified" | "not_present";
        /**
         * WorkspaceOverview
         * @description Everything the interface needs for a cold start, in one request.
         */
        WorkspaceOverview: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Schema Version
             * @description Null when no schema has been agreed yet.
             */
            schema_version?: number | null;
            /** Fields */
            fields?: components["schemas"]["FieldSpec"][];
            /** Documents */
            documents?: components["schemas"]["DocumentSummary"][];
            /**
             * Record Count
             * @default 0
             */
            record_count: number;
            /**
             * Last Event Seq
             * @description The newest event sequence number. The interface opens its event stream with this as Last-Event-ID, so a cold start streams only what happens NEXT rather than replaying the entire history it has just loaded.
             * @default 0
             */
            last_event_seq: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_workspace_api_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_v1_workspaces__workspace_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_workspaces__workspace_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_api_v1_workspaces__workspace_id__documents_seed_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_workspaces__workspace_id__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document identifier. */
                document_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_workspaces__workspace_id__documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document identifier. */
                document_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    original_file_api_v1_workspaces__workspace_id__documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document identifier. */
                document_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_image_api_v1_workspaces__workspace_id__documents__document_id__pages__page_index__image_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document identifier. */
                document_id: string;
                page_index: number;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reextract_api_v1_workspaces__workspace_id__documents__document_id__reextract_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document identifier. */
                document_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReextractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_records_api_v1_workspaces__workspace_id__records_get: {
        parameters: {
            query?: {
                /** @description From a previous page. */
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_field_api_v1_workspaces__workspace_id__records__record_id__fields__field_key__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Record identifier. */
                record_id: string;
                field_key: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldValue"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_api_v1_workspaces__workspace_id__review_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueue"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_v1_workspaces__workspace_id__schema_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_schema_api_v1_workspaces__workspace_id__schema_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSchemaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schema_history_api_v1_workspaces__workspace_id__schema_versions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_schema_api_v1_workspaces__workspace_id__schema_revert_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_v1_workspaces__workspace_id__proposals_get: {
        parameters: {
            query?: {
                include_resolved?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_proposal_api_v1_workspaces__workspace_id__proposals__proposal_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                proposal_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_workspaces__workspace_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
