/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and readiness */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an anonymous workspace */
        post: operations["create_workspace_api_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema, documents, and counts for a cold start */
        get: operations["get_workspace_api_v1_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload one or more documents */
        post: operations["upload_api_v1_workspaces__workspace_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load the sample documents
         * @description Load the curated sample set. Requirement FR-05, decision D15.
         *
         *     Reads ``samples/manifest.json`` rather than hard-coding filenames, so dropping files
         *     into ``samples/`` is the only step needed to change the demo corpus.
         */
        post: operations["seed_api_v1_workspaces__workspace_id__documents_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One document */
        get: operations["get_document_api_v1_workspaces__workspace_id__documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete a document */
        delete: operations["delete_document_api_v1_workspaces__workspace_id__documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The original file, with byte-range support
         * @description Stream the original. Range requests are supported because pdf.js relies on them.
         *
         *     Without ranges, opening page one of a fifty megabyte scan downloads all fifty
         *     megabytes first, which is the difference between a viewer that feels instant and one
         *     that does not.
         */
        get: operations["original_file_api_v1_workspaces__workspace_id__documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents/{document_id}/pages/{page_index}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A rendered page image */
        get: operations["page_image_api_v1_workspaces__workspace_id__documents__document_id__pages__page_index__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents/{document_id}/reextract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-run extraction, preserving human corrections
         * @description Re-run the pipeline for one document. Requirement FR-34.
         *
         *     Human-verified values survive by construction: the write path filters them out and a
         *     disagreeing model answer is recorded beside the human's rather than over it. See
         *     ``app.pipeline.persist`` and decision D16.
         */
        post: operations["reextract_api_v1_workspaces__workspace_id__documents__document_id__reextract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Records, cursor paged */
        get: operations["list_records_api_v1_workspaces__workspace_id__records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/records/{record_id}/fields/{field_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Correct one value
         * @description Record a human decision about one value. Requirements FR-23 and FR-34.
         *
         *     From this point the value is immune to re-extraction: the write path filters
         *     human-owned rows, and a later model answer that disagrees is stored beside it rather
         *     than over it (decision D16).
         */
        patch: operations["correct_field_api_v1_workspaces__workspace_id__records__record_id__fields__field_key__patch"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current schema */
        get: operations["get_schema_api_v1_workspaces__workspace_id__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename or merge a field */
        patch: operations["update_schema_api_v1_workspaces__workspace_id__schema_patch"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live workspace events (Server-Sent Events) */
        get: operations["events_api_v1_workspaces__workspace_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conversation history
         * @description Persisted state only. A streaming answer's text lives in its buffer until it
         *     finishes, so a message here that says ``streaming`` has empty content on purpose: the
         *     client opens its stream to get the rest.
         */
        get: operations["list_messages_api_v1_workspaces__workspace_id__chat_messages_get"];
        put?: never;
        /** Ask a question */
        post: operations["ask_api_v1_workspaces__workspace_id__chat_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/chat/messages/{message_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The answer, streamed (Server-Sent Events) */
        get: operations["stream_api_v1_workspaces__workspace_id__chat_messages__message_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/chat/messages/{message_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop a streaming answer
         * @description Cancel generation. What already streamed is kept.
         *
         *     Keeping the partial text is deliberate: the user read it, so deleting it would be
         *     surprising, and a stopped answer has often already said the useful part.
         */
        post: operations["stop_api_v1_workspaces__workspace_id__chat_messages__message_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/chat/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggested questions */
        get: operations["suggestions_api_v1_workspaces__workspace_id__chat_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current dashboard
         * @description Persisted panels. Requirement FR-34: a refresh never re-runs generation.
         */
        get: operations["get_dashboard_api_v1_workspaces__workspace_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/dashboard/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate the dashboard
         * @description Plan, evaluate, vet, and persist.
         *
         *     Synchronous, unlike a chat answer. A dashboard is one structured call and a handful of
         *     in-process evaluations, so it completes in about a second on the fast tier, and the
         *     user pressed a button and is watching. Streaming it would add a second connection to
         *     reason about for no gain the user could perceive.
         */
        post: operations["generate_api_v1_workspaces__workspace_id__dashboard_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /**
         * AskResponse
         * @description 202. Generation has started; the answer arrives on the stream.
         */
        AskResponse: {
            user_message: components["schemas"]["MessageResponse"];
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /**
             * Stream Url
             * @description Where to read the answer. Given rather than constructed by the client so the route can move without breaking it.
             */
            stream_url: string;
        };
        /**
         * BBox
         * @description An axis-aligned box in top-left-origin page points. See the module docstring.
         */
        BBox: {
            /**
             * X0
             * @description Left edge, points from the left of the page.
             */
            x0: number;
            /**
             * Top
             * @description Top edge, points from the TOP of the page.
             */
            top: number;
            /**
             * X1
             * @description Right edge, points from the left of the page.
             */
            x1: number;
            /**
             * Bottom
             * @description Bottom edge, points from the TOP of the page.
             */
            bottom: number;
        };
        /** Body_upload_api_v1_workspaces__workspace_id__documents_post */
        Body_upload_api_v1_workspaces__workspace_id__documents_post: {
            /**
             * Files
             * @description One or more documents.
             */
            files: string[];
        };
        /** CheckResult */
        CheckResult: {
            /** Ok */
            ok: boolean;
            /** Detail */
            detail?: string | null;
        };
        /**
         * CorrectionRequest
         * @description Either a value, or an assertion that the field is absent from this document.
         */
        CorrectionRequest: {
            /** Value */
            value?: unknown | null;
            /**
             * Not Present
             * @description The user asserts this document does not contain this field. A correction in its own right, and protected from re-extraction the same way an edited value is.
             * @default false
             */
            not_present: boolean;
        };
        /** CreateWorkspaceRequest */
        CreateWorkspaceRequest: {
            /** Label */
            label?: string | null;
        };
        /** CreateWorkspaceResponse */
        CreateWorkspaceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Token
             * @description Bearer token for every subsequent request. Returned ONCE and never recoverable: only its hash is stored. Anyone holding it has full access to this workspace, which is the accepted tradeoff of having no accounts (decision D8).
             */
            token: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Status */
            status: string;
            /**
             * Stale
             * @description Documents were added or values corrected since generation. The interface offers to regenerate rather than doing it unasked, because regeneration is a model call.
             */
            stale: boolean;
            /** Panels */
            panels?: components["schemas"]["PanelResponse"][];
            /** Generated At */
            generated_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Mime */
            mime: string;
            source_format: components["schemas"]["SourceFormat"];
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["DocumentStatus"];
            /** Stage Detail */
            stage_detail: string | null;
            /** Failure Reason */
            failure_reason: string | null;
            /** Page Count */
            page_count: number | null;
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Pages
             * @description Per-page dimensions IN POINTS plus the image path. The viewer divides the width it actually rendered by `width_pt` to get its overlay scale, so it never needs to know about dots per inch.
             */
            pages?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DocumentStatus
         * @description Where a document is in the pipeline. Rendered directly as the processing strip.
         *
         *     The observability requirement and the user experience are the same feature here: the
         *     strip in the interface IS this state machine, so every state has to be one a person
         *     would want to see, and every transition publishes an event.
         *
         *     Transitions::
         *
         *         uploaded -> parsing -> extracting -> indexing -> done
         *              |          |           |            |
         *              +----------+-----------+------------+--> failed
         *
         *     ``indexing`` is where a document is chunked and embedded. It matters that it is a
         *     visible stage rather than a silent tail of extraction: a document is not askable until
         *     it is indexed, so ``done`` means "in the table AND in the chat", which is the promise
         *     section 6.3 of the implementation document makes.
         *
         *     AWAITING_SCHEMA IS INTERNAL AND IS NOT PART OF THE WIRE VOCABULARY
         *     ------------------------------------------------------------------
         *     A document in the very first batch finishes open extraction before the workspace has a
         *     schema, so it cannot produce records yet. The worker needs to tell that apart from a
         *     document still mid-model-call, so the distinction is a real database status.
         *
         *     It is deliberately **not** one of the six statuses in the interface contract
         *     (implementation.md section 5.1). On the wire it is reported as ``extracting`` with a
         *     ``stage_detail`` of "waiting for the rest of the batch", which is honest (the document
         *     is still inside the extraction phase) and keeps the client's state machine to the six
         *     states the contract names. ``for_wire`` is that mapping, in one place.
         * @enum {string}
         */
        DocumentStatus: "uploaded" | "parsing" | "extracting" | "awaiting_schema" | "indexing" | "done" | "failed";
        /** DocumentSummary */
        DocumentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            status: components["schemas"]["DocumentStatus"];
            /** Stage Detail */
            stage_detail?: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Page Count */
            page_count?: number | null;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FieldSpec
         * @description One field in a workspace's schema, as the user has agreed to it.
         */
        FieldSpec: {
            /**
             * Key
             * @description Column name in the generated view. Machine identifier.
             */
            key: string;
            /**
             * Label
             * @description What the interface shows a person.
             */
            label: string;
            type: components["schemas"]["FieldType"];
            /**
             * Description
             * @description What this field means. Sent to the model during schema-guided extraction, and used for similarity matching during drift detection.
             * @default
             */
            description: string;
            /**
             * Enum Values
             * @description Permitted values, for FieldType.ENUM only.
             */
            enum_values?: string[] | null;
            /**
             * Currency Default
             * @description ISO 4217 code assumed when a document states an amount with no currency marker, for FieldType.CURRENCY only.
             */
            currency_default?: string | null;
            /**
             * Source Keys
             * @description The raw keys from open extraction that were unified into this field. Kept so the user can see WHY a field exists, and so drift detection knows which aliases have already been resolved.
             */
            source_keys?: string[];
            /**
             * Weight
             * @description Review priority multiplier. The review queue orders by weight * (1 - confidence), so a wrong total matters more than a wrong note. Currency and date fields default higher, set in app.schema.propose.
             * @default 1
             */
            weight: number;
        };
        /**
         * FieldType
         * @description The supported field types. Requirement FR-12.
         *
         *     The stored representation of each is documented in ``app.domain.values``, which is the
         *     only module that converts between a raw model output and one of these.
         * @enum {string}
         */
        FieldType: "string" | "number" | "currency" | "date" | "boolean" | "enum" | "string_list";
        /**
         * FieldValue
         * @description One extracted or corrected value, with everything needed to trust it.
         */
        FieldValue: {
            /** Field Key */
            field_key: string;
            /**
             * Value
             * @description The value, in the stored representation for its type. Null means the field is genuinely absent from this document, not that extraction failed.
             */
            value?: unknown | null;
            value_type: components["schemas"]["FieldType"];
            /**
             * Confidence
             * @description The model's self-report. Never the tier.
             */
            confidence?: number | null;
            tier: components["schemas"]["Tier"];
            /** @default model */
            status: components["schemas"]["ValueStatus"];
            provenance?: components["schemas"]["Provenance"] | null;
            /** Model Value */
            model_value?: unknown | null;
            /** Model Value At */
            model_value_at?: string | null;
        };
        /**
         * GroundingFailure
         * @description Why a value could not be located in its document.
         *
         *     Recorded rather than swallowed. A value that cannot be grounded has its tier capped at
         *     low (see ``app.pipeline.score``), and this is the reason the interface shows the user.
         *     An ungroundable value is the strongest hallucination signal we have: a value the model
         *     invented has no quote to find. See decision D5.
         * @enum {string}
         */
        GroundingFailure: "no_quote" | "quote_not_found" | "page_out_of_range" | "no_text_layer";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Environment */
            environment: string;
            /**
             * Process Id
             * @description Operating system process identifier. The in-process worker queue and event bus require exactly one API process, so seeing this value change between requests means the deployment is misconfigured. See decision D9.
             */
            process_id: number;
            database: components["schemas"]["CheckResult"];
            storage: components["schemas"]["CheckResult"];
            llm: components["schemas"]["CheckResult"];
        };
        /** MergeOperation */
        MergeOperation: {
            /**
             * From
             * @description The field to absorb. It disappears.
             */
            from: string;
            /**
             * Into
             * @description The field that survives.
             */
            into: string;
        };
        /** MessageList */
        MessageList: {
            /** Messages */
            messages: components["schemas"]["MessageResponse"][];
        };
        /** MessageResponse */
        MessageResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /** Content */
            content: string;
            /** Sources */
            sources?: {
                [key: string]: unknown;
            }[];
            /** Citations */
            citations?: {
                [key: string]: unknown;
            }[];
            /** Visual */
            visual?: {
                [key: string]: unknown;
            } | null;
            /** Surface */
            surface?: {
                [key: string]: unknown;
            }[] | null;
            /** Error */
            error?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** PanelResponse */
        PanelResponse: {
            /** Title */
            title: string;
            /** Kind */
            kind: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Query */
            query?: {
                [key: string]: unknown;
            };
            /**
             * Surface
             * @description A complete A2UI message array. The numbers live in its updateDataModel message and were computed by the server (decision D37).
             */
            surface?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * Provenance
         * @description The trail from a value back to the pixels it came from.
         *
         *     An empty ``boxes`` list with a populated ``failure`` is a legitimate, fully described
         *     state: we have a value, we know the model's justification for it, and we are telling the
         *     user honestly that we could not find that justification in the document.
         */
        Provenance: {
            /**
             * Page Index
             * @description Zero-based page the value was found on, if known.
             */
            page_index?: number | null;
            /**
             * Boxes
             * @description One box per visual line of the matched quote. Empty means grounding failed, in which case `failure` says why. Multiple boxes rather than one union box, because a quote that wraps must not highlight the content between its fragments (requirement FR-30).
             */
            boxes?: components["schemas"]["BBox"][];
            /**
             * Quote
             * @description The verbatim span the model cited as evidence. Shown to the user in the viewer side card (requirement FR-31).
             */
            quote?: string | null;
            /**
             * Reasoning
             * @description The model's short justification for this value. FR-31.
             */
            reasoning?: string | null;
            /**
             * Match Score
             * @description Fuzzy match score of the quote against the page text, 0 to 100. Feeds tier derivation.
             */
            match_score?: number | null;
            /**
             * Locator
             * @description Human-readable address within the source, for formats where one is meaningful: 'Sheet1!B7', 'paragraph 12', 'line 48'. Display only, never parsed.
             */
            locator?: string | null;
            /** @description Set if and only if `boxes` is empty. */
            failure?: components["schemas"]["GroundingFailure"] | null;
        };
        /**
         * Record
         * @description One row of the unified table.
         */
        Record: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Document Name
             * @description Original filename. Shown as the row's identity.
             */
            document_name: string;
            /** Schema Version */
            schema_version: number;
            /**
             * Values
             * @description Keyed by field key. A field absent from this mapping was never extracted for this document, which is different from a field present with a null value, which means the document genuinely does not contain it.
             */
            values?: {
                [key: string]: components["schemas"]["FieldValue"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RecordPage
         * @description A cursor-paged slice of records.
         */
        RecordPage: {
            /** Records */
            records: components["schemas"]["Record"][];
            /**
             * Next Cursor
             * @description Opaque. Pass back as `cursor` for the next page.
             */
            next_cursor?: string | null;
            /**
             * Total
             * @description Total records in the workspace, for the row count.
             */
            total: number;
        };
        /** ReextractResponse */
        ReextractResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Message */
            message: string;
        };
        /** RejectedUpload */
        RejectedUpload: {
            /** Filename */
            filename: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** RenameOperation */
        RenameOperation: {
            /** From */
            from: string;
            /** To */
            to: string;
            /**
             * Label
             * @description New display label. Defaults to keeping the current one.
             */
            label?: string | null;
        };
        /** SchemaResponse */
        SchemaResponse: {
            /** Version */
            version: number | null;
            /** Fields */
            fields?: components["schemas"]["FieldSpec"][];
        };
        /** SeedResponse */
        SeedResponse: {
            /** Loaded */
            loaded?: components["schemas"]["UploadedDocument"][];
            /** Missing */
            missing?: string[];
            /** Message */
            message: string;
        };
        /**
         * SourceFormat
         * @description Formats Distill can parse. Requirement FR-02.
         * @enum {string}
         */
        SourceFormat: "pdf" | "image" | "docx" | "xlsx" | "csv" | "text";
        /** SuggestionsResponse */
        SuggestionsResponse: {
            /** Questions */
            questions?: string[];
        };
        /**
         * Tier
         * @description How much a value should be trusted. Always DERIVED, never asked of the model.
         *
         *     See decision D5 and the table in implementation.md section 6.4. The derivation lives in
         *     ``app.pipeline.score`` and nowhere else.
         * @enum {string}
         */
        Tier: "high" | "medium" | "low" | "conflict" | "verified";
        /**
         * UpdateSchemaRequest
         * @description One operation per request. Requirement FR-15.
         *
         *     Deliberately not "here is the whole new field list". A whole-list edit makes every
         *     change look the same to the server, which then has to infer what the user meant by
         *     diffing, and a rename is indistinguishable from a delete plus an add. That matters
         *     because a merge has to MOVE values and a rename must not, so the distinction cannot be
         *     left to inference.
         */
        UpdateSchemaRequest: {
            rename?: components["schemas"]["RenameOperation"] | null;
            merge?: components["schemas"]["MergeOperation"] | null;
        };
        /**
         * UploadResponse
         * @description Partial success is the normal case, so accepted and rejected come back together.
         *
         *     One unreadable file in a drop of twelve must not fail the other eleven, which is
         *     guarantee 3 in the backend plan and requirement 3.6.
         */
        UploadResponse: {
            /** Accepted */
            accepted?: components["schemas"]["UploadedDocument"][];
            /** Rejected */
            rejected?: components["schemas"]["RejectedUpload"][];
        };
        /** UploadedDocument */
        UploadedDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            status: components["schemas"]["DocumentStatus"];
            /** Size Bytes */
            size_bytes: number;
            source_format: components["schemas"]["SourceFormat"];
            /** Detected Mime */
            detected_mime: string;
            /**
             * Note
             * @description Set when the file's contents disagree with its extension. The content decides which parser runs; this explains what we concluded.
             */
            note?: string | null;
            /**
             * Duplicate Of
             * @description Set when this exact file is already in the workspace. The upload is accepted and points at the existing document rather than processing it twice.
             */
            duplicate_of?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValueStatus
         * @description Where a value came from. Drives the never-lose-a-correction guarantee.
         *
         *     Every write path a model can reach filters on ``status <> 'human_verified'``. This is
         *     enforced in SQL rather than by convention, which is what makes principle 4 of
         *     requirements.md a guarantee instead of an intention.
         * @enum {string}
         */
        ValueStatus: "model" | "human_verified" | "not_present";
        /**
         * WorkspaceOverview
         * @description Everything the interface needs for a cold start, in one request.
         */
        WorkspaceOverview: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Schema Version
             * @description Null when no schema has been agreed yet.
             */
            schema_version?: number | null;
            /** Fields */
            fields?: components["schemas"]["FieldSpec"][];
            /** Documents */
            documents?: components["schemas"]["DocumentSummary"][];
            /**
             * Record Count
             * @default 0
             */
            record_count: number;
            /**
             * Dashboard Status
             * @description pending, ready, or failed. Null when no dashboard row exists yet.
             */
            dashboard_status?: string | null;
            /**
             * Dashboard Stale
             * @default false
             */
            dashboard_stale: boolean;
            /**
             * Dashboard Panel Count
             * @default 0
             */
            dashboard_panel_count: number;
            /**
             * Last Event Seq
             * @description The newest event sequence number. The interface opens its event stream with this as Last-Event-ID, so a cold start streams only what happens NEXT rather than replaying the entire history it has just loaded.
             * @default 0
             */
            last_event_seq: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_workspace_api_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_v1_workspaces__workspace_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_workspaces__workspace_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_api_v1_workspaces__workspace_id__documents_seed_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_workspaces__workspace_id__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document identifier. */
                document_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_workspaces__workspace_id__documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document identifier. */
                document_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    original_file_api_v1_workspaces__workspace_id__documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document identifier. */
                document_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_image_api_v1_workspaces__workspace_id__documents__document_id__pages__page_index__image_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document identifier. */
                document_id: string;
                page_index: number;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reextract_api_v1_workspaces__workspace_id__documents__document_id__reextract_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Document identifier. */
                document_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReextractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_records_api_v1_workspaces__workspace_id__records_get: {
        parameters: {
            query?: {
                /** @description From a previous page. */
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_field_api_v1_workspaces__workspace_id__records__record_id__fields__field_key__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                /** @description Record identifier. */
                record_id: string;
                field_key: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldValue"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_v1_workspaces__workspace_id__schema_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_schema_api_v1_workspaces__workspace_id__schema_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSchemaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_workspaces__workspace_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_v1_workspaces__workspace_id__chat_messages_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_v1_workspaces__workspace_id__chat_messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_v1_workspaces__workspace_id__chat_messages__message_id__stream_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
                authorization?: string | null;
            };
            path: {
                message_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_api_v1_workspaces__workspace_id__chat_messages__message_id__stop_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                message_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggestions_api_v1_workspaces__workspace_id__chat_suggestions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_v1_workspaces__workspace_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_v1_workspaces__workspace_id__dashboard_generate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
